cloudposse/atmos

- README.md
- README.yaml
- example/Dockerfile
- example/Makefile
- example/cli/main.variant
* Rename resources and update README
* Rename resources and update README after the repo name changed
> Rename resources and update README

- modules/terraform/terraform-backend.variant
* Add pretty-printing of JSON in `backend.tf.json` file
* So that it is easier to read and any diffs are easier to view/reason about what has changed
> add pretty printing for backend.tf.json

- atmos/modules/terraform/terraform-core.variant
- atmos/modules/terraform/terraform-import.variant
* Pass `region` parameter for `terraform import`
* `terraform import` was broken
> AWS region paramater pass for terraform import

- README.yaml
* add install instructions
* easy install instructions
* Closes https://github.com/cloudposse/atmos/issues/79
* https://formulae.brew.sh/formula/atmos
> Add install instructions

- examples/complete/Dockerfile
- examples/complete/README.md
- internal/exec/helmfile.go
- internal/exec/terraform.go
- pkg/config/utils.go
* Various fixes
* Bump `geodesic` version
* Address the comments from https://github.com/cloudposse/atmos/pull/108
> Various fixes

- README.md
- README.yaml
* Fix spacing, add console highlight
* Easier to copy and paste code
* N/A
> README: Fix spacing, add console highlight

- .github/workflows/website-deploy-preview.yml
- .github/workflows/website-deploy-release.yml
- .github/workflows/website-destroy-preview.yml
- Update name of GitHub Action IAM role used to maintain website
- New Cloud Posse naming convention
> Update name of GitHub Action IAM role

- README.md
- README.yaml
- internal/exec/shell_utils.go
* Add `TF_CLI_ARGS_console` env var to `shell` subcommand
* Saves me from having to pass in the `-var-file` to `terraform console`
- https://www.terraform.io/cli/config/environment-variables
> Add `TF_CLI_ARGS_console` env var to `shell` subcommand

- website/docs/core-concepts/stacks/mixins.md
* Doc update to help clarify the section for the vars
Note: unsure if this is required, but I'm pretty sure that's needed. :)
* This doc doesn't show the expected section for the `stage` var
> Update docs to clarify vars ref

- .github/workflows/website-deploy-preview.yml
- .github/workflows/website-deploy-release.yml
- website/algolia/reindex.sh
- website/algolia/template.json
- website/docs/tutorials/atmos-getting-started.md
- website/docs/tutorials/first-aws-environment.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
* Added Algolia search integration
* Decided to use Algolia search for atmos docs as well
> Added Algolia search integration

- website/Brewfile.lock.json
- website/src/theme/NotFound.js
Fixed 404 page
More user friendly 404 page
> Fixed 404 page

- .github/workflows/website-deploy-release.yml
- website/docusaurus.config.js
- Use consolidated index between atmos.tools and docs.cloudposse.com
- Use consolidated index between atmos.tools and docs.cloudposse.com
> Consolidated index

- website/docusaurus.config.js
- New top Nav Bar menu items
- New top Nav Bar menu items
> New top Nav Bar menu items

- website/docs/integrations/github-actions/component-updater.md
* Updated docs for component-updater to include few more usage examples
* Enriched docs
> Updated docs for component-updater

- website/docs/core-concepts/stacks/stacks.md
- Fixed description for Stacks page
- Page description didn't match page content.
> Fixed description for Stacks page

- website/docs/quick-start/configure-cli.md
- website/docs/quick-start/create-atmos-stacks.md
- Fixed typos in Quick Start pages
- Fixed typos in Quick Start pages
> Fixed typos in Quick Start pages

- website/docs/integrations/github-actions/atmos-terraform-plan.md
- updated documentation for the dynamodb table required for `github-actions-atmos-terraform-plan/apply`
- updated the requirements for triggering on merges
- https://github.com/cloudposse/github-action-terraform-plan-storage/pull/16
> Update documentation for `gitops/dynamodb`

- .github/dependabot.yml
- ci: add npm to dependabot
- This should cover the remaining items found in dependabot
- https://github.com/cloudposse/atmos/security/dependabot
> ci: add npm to dependabot

- .github/workflows/codeql.yml
- ci(code-scanning): add codeql.yml
- codeql is free, github official, and uses sast and dast to scan the code to find vulnerabilities
- It's used in runatlantis/atlantis and powerful!
- https://github.com/cloudposse/atmos/actions/new?category=security&query=code+scanning
- https://codeql.github.com/
- https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql
> ci(code-scanning): add codeql.yml

- website/docs/quick-start/create-atmos-stacks.md
Fixing typo in stack yaml title
Many title in the stack example code contain a typo
Improving documentation
> fixing typo

- .github/workflows/vhs.yaml
- website/src/css/custom.css
- website/src/pages/index.js
- Use % instead of vw, since the outter container is capped at a certain px size.
- Set a minimum height of the header in px, otherwise if based on vh it can be impossibly small and gets eaten by the nav bar
- Move the footer outside of main, so it's consistent with the header.
- New landing page introduced in #540 wasn't tested on all screensizes
> Fix responsiveness of css

- website/docs/integrations/github-actions/component-updater.md
- Updated the setup steps required for creating and installing a GitHub App
- These steps can be overlooked but are required
- n/a
> chore: Improved Component Updater Setup Steps

- website/docs/integrations/github-actions/github-actions.mdx
* [docs] Integration GHA fix version compatibility table
* Table in tip box looks ugly
> [docs] Integration GHA fix version compatibility table

- .github/workflows/dependabot.yml
Check for approved licenses
Avoid accidentally introducing code that is non-permissively licensed
> Introduce License Check

- internal/exec/terraform_plan_diff.go
> fix plan-diff test
